default_stages: [commit]

default_language_version:
  python: python3.10

repos:

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: make-badges
        name: make-badges
        entry: get_badges.py
        language: script
        pass_filenames: false
        verbose: true
