version: "3.9"

services:

  docx:
    hostname: docx
    container_name: docx
    restart: unless-stopped
    ports:
      - $API_PORT_INTERNAL:$API_PORT_INTERNAL
    env_file:
      - .env
    tty: true
    init: true
    volumes:
      - ./src/docx/.history:/home/appuser/commandhistory
      - ./downloads:/home/appuser/src/downloads

    networks:
      - netname

networks:
  netname:
    name: $NET_NAME
