version: "3.9"

services:

  doct:
    build:
      context: .
      dockerfile: Dockerfile
#    command:
#      - bash 'ls -al'
#    entrypoint: bash
    hostname: doct
    container_name: doct
    tty: true
    init: true
    volumes:
      - ./downloads:/home/appuser/src/downloads
      - ./docx_tpl/.history:/home/appuser/commandhistory

    networks:
      - netname

networks:
  netname:
    name: $NET_NAME
