[tool.poetry]
name = "docx-tpl"
version = "0.1.0"
description = ""
authors = ["Mavlin Dm. <mavlind@list.ru>"]
readme = "README.md"
packages = [{include = "docx_tpl"}]

[tool.poetry.dependencies]
python = "^3.9"
docxtpl = "^0.16.5"
fastapi = "^0.92.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
logrich = "^0.7.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
watchdog = "^2.3.1"
pytest = "^7.2.2"
httpx = "^0.23.3"
asgi-lifespan = "^2.0.0"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 100
include = '\.pyi?$'
quiet = true
fast = true
